runtime: nodejs14
service: default

env_variables:
  REACT_APP_API_URL: "https://www.ssitechsolution.tech/api/save-data"

handlers:
  - url: /static
    static_files: build/static
    upload: build/static/(.*)

  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
