runtime: python39
service: default

env_variables:
  REACT_APP_API_URL: "https://www.ssitechsolution.tech/api/save-data"
  FIREBASE_API_KEY: "your_firebase_api_key"  # Replace with actual API key
  FIREBASE_AUTH_DOMAIN: "your_project_id.firebaseapp.com"  # Replace with actual auth domain
  FIREBASE_PROJECT_ID: "your_project_id"  # Replace with actual project ID
  FIREBASE_STORAGE_BUCKET: "your_project_id.appspot.com"  # Replace with actual storage bucket
  FIREBASE_MESSAGING_SENDER_ID: "your_messaging_sender_id"  # Replace with actual messaging sender ID
  FIREBASE_APP_ID: "your_app_id"  # Replace with actual app ID

handlers:
  - url: /static
    static_files: build/static
    upload: build/static/(.*)

  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
