runtime: nodejs18
env: standard

instance_class: F2
entrypoint: npm run start

handlers:
  # Serve static files from the 'build/static' directory
  - url: /static
    static_dir: build/static

  # Serve the index.html file for React frontend routing
  - url: /
    static_files: build/index.html
    upload: build/index.html

  # Serve favicon, manifest, and robots.txt
  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico

  - url: /manifest.json
    static_files: build/manifest.json
    upload: build/manifest.json

  - url: /robots.txt
    static_files: build/robots.txt
    upload: build/robots.txt

  # Catch-all for API requests routed to the backend
  - url: /api/.*
    script: auto

  # Catch-all for React frontend routing
  - url: /.*
    script: auto

env_variables:
  PORT: 5000
  BUCKET_NAME: "ssi-tech-solution"  # Replace with your actual bucket name
  REACT_APP_CONTACT_API: '["http://www.ssitechsolution.tech/api/save-data", "http://ssitechsolution/api/save-data"]'  # Backend API URL
