runtime: nodejs18
service: backend  # You can change this service name if needed

env_variables:
  BUCKET_NAME: "backed_data"
  CORS_ORIGIN: "https://www.ssitechsolution.tech"
  NODE_ENV: "production"
  FIREBASE_API_KEY: "your_firebase_api_key"  # Replace with actual API key
  FIREBASE_AUTH_DOMAIN: "your_project_id.firebaseapp.com"  # Replace with actual auth domain
  FIREBASE_PROJECT_ID: "your_project_id"  # Replace with actual project ID
  FIREBASE_STORAGE_BUCKET: "your_project_id.appspot.com"  # Replace with actual storage bucket
  FIREBASE_MESSAGING_SENDER_ID: "your_messaging_sender_id"  # Replace with actual messaging sender ID
  FIREBASE_APP_ID: "your_app_id"  # Replace with actual app ID

handlers:
  - url: /.*
    script: auto  # Directs all traffic to server.js

instance_class: F1  # Cost-efficient instance type
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Ensure the server runs on the correct port
entrypoint: node server.js
